// Native browser print — no jsPDF dependency required for transcript export.
import { apiRequest } from "@/api/client";
import type { ChatMessage } from "@/lib/store";

function stripMarkdown(text: string): string {
  return text
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[#>*_~]/g, "")
    .trim();
}

export async function exportChatPdf(messages: ChatMessage[], activeCaseId: string | null): Promise<void> {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow pop-ups to export the PDF.");
    return;
  }

  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Copilot_Transcript_${Date.now()}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
          body { 
            font-family: 'Inter', system-ui, -apple-system, sans-serif; 
            padding: 40px; 
            color: #1e293b; 
            max-width: 850px; 
            margin: 0 auto; 
            line-height: 1.6; 
            background-color: #ffffff;
          }
          .header { 
            border-bottom: 2px solid #e2e8f0; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
            text-align: center;
          }
          .title { 
            font-size: 24px; 
            font-weight: 700; 
            color: #0f172a; 
            margin: 0 0 10px 0; 
            letter-spacing: -0.02em;
          }
          .meta { 
            font-size: 13px; 
            color: #64748b; 
            margin: 4px 0; 
            font-weight: 500;
          }
          .chat-container {
            display: flex;
            flex-direction: column;
            gap: 20px;
          }
          .message { 
            display: flex;
            flex-direction: column;
            max-width: 85%;
          }
          .message.officer {
            align-self: flex-end;
          }
          .message.copilot {
            align-self: flex-start;
          }
          .speaker { 
            font-size: 11px; 
            font-weight: 700; 
            text-transform: uppercase; 
            letter-spacing: 0.05em; 
            margin-bottom: 6px; 
          }
          .officer .speaker { color: #475569; text-align: right; }
          .copilot .speaker { color: #0d9488; text-align: left; }
          .content { 
            font-size: 14px; 
            white-space: pre-wrap; 
            padding: 16px 20px;
            border-radius: 12px;
            box-shadow: 0 1px 2px rgba(0,0,0,0.05);
          }
          .officer .content { 
            background-color: #f1f5f9; 
            color: #0f172a;
            border: 1px solid #e2e8f0;
            border-bottom-right-radius: 4px;
          }
          .copilot .content { 
            background-color: #f0fdfa; 
            color: #0f172a;
            border: 1px solid #ccfbf1;
            border-bottom-left-radius: 4px;
          }
          .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 class="title">SCRB Sahayak AI Transcript</h1>
          <p class="meta">Generated on ${new Date().toLocaleString()}</p>
          ${activeCaseId ? `<p class="meta">Active Case Reference: <strong>${activeCaseId}</strong></p>` : ""}
        </div>
        <div class="chat-container">
  `;

  for (const message of messages) {
    const isUser = message.role === "user";
    const speaker = isUser ? "OFFICER" : "COPILOT";
    const text = stripMarkdown(message.content || "");

    html += `
          <div class="message ${isUser ? "officer" : "copilot"}">
            <div class="speaker">${speaker}</div>
            <div class="content">${text.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
          </div>
    `;
  }

  html += `
        </div>
        <div class="footer">
          Official transcript generated by SCRB Sahayak Investigation Copilot.
        </div>
      </body>
      <script>
        window.onload = () => {
          setTimeout(() => { window.print(); }, 500);
        };
      </script>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();

  try {
    await apiRequest("/api/audit", {
      method: "POST",
      body: JSON.stringify({
        action: "EXPORT_CHAT_PDF",
        targetType: "CHAT",
        targetId: activeCaseId || null,
        details: `Exported a ${messages.length}-message transcript`,
      }),
    });
  } catch {
    // The PDF already saved client-side; a failed audit write shouldn't block the officer.
  }
}
